Repository Flux2024/Flux_BackServer, pull requests merged in 2024-08, with the labels that each got.

#32 feat : login backserver
  .gitignore
  build.gradle
  src/main/java/com/flux/application/FluxApplication.java
  src/main/java/com/flux/fluxDomainLogin/controller/SampleController.java
  src/main/java/com/flux/fluxDomainLogin/model/DTO.java
  src/main/java/com/flux/fluxDomainLogin/model/Entitiy.java
  src/main/java/com/flux/fluxDomainLogin/repository/SampleRepository.java
  src/main/java/com/flux/fluxDomainLogin/service/SampleService.java
Labels: developing

#36 feat : login
  src/main/java/com/flux/application/FluxApplication.java
  src/main/java/com/flux/fluxDomainLogin/config/AppProperties.java
  src/main/java/com/flux/fluxDomainLogin/config/SecurityConfig.java
  src/main/java/com/flux/fluxDomainLogin/config/WebMvcConfig.java
  src/main/java/com/flux/fluxDomainLogin/controller/AuthController.java
  src/main/java/com/flux/fluxDomainLogin/controller/MainController.java
  src/main/java/com/flux/fluxDomainLogin/controller/UserController.java
  src/main/java/com/flux/fluxDomainLogin/exception/BadRequestException.java
  src/main/java/com/flux/fluxDomainLogin/exception/GlobalExceptionHandler.java
  src/main/java/com/flux/fluxDomainLogin/exception/OAuth2AuthenticationProcessingException.java
  src/main/java/com/flux/fluxDomainLogin/exception/ResourceNotFoundException.java
  src/main/java/com/flux/fluxDomainLogin/model/AuthProvider.java
  src/main/java/com/flux/fluxDomainLogin/model/User.java
  src/main/java/com/flux/fluxDomainLogin/payload/ApiResponse.java
  src/main/java/com/flux/fluxDomainLogin/payload/AuthResponse.java
  src/main/java/com/flux/fluxDomainLogin/payload/LoginRequest.java
  src/main/java/com/flux/fluxDomainLogin/payload/SignUpRequest.java
  src/main/java/com/flux/fluxDomainLogin/repository/UserRepository.java
  src/main/java/com/flux/fluxDomainLogin/security/CurrentUser.java
  src/main/java/com/flux/fluxDomainLogin/security/CustomUserDetailsService.java
  src/main/java/com/flux/fluxDomainLogin/security/RestAuthenticationEntryPoint.java
  src/main/java/com/flux/fluxDomainLogin/security/TokenAuthenticationFilter.java
  src/main/java/com/flux/fluxDomainLogin/security/TokenProvider.java
  src/main/java/com/flux/fluxDomainLogin/security/UserPrincipal.java
  src/main/java/com/flux/fluxDomainLogin/security/oauth2/CustomOAuth2UserService.java
  src/main/java/com/flux/fluxDomainLogin/security/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/flux/fluxDomainLogin/security/oauth2/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/flux/fluxDomainLogin/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/flux/fluxDomainLogin/security/oauth2/user/GoogleOAuth2UserInfo.java
  src/main/java/com/flux/fluxDomainLogin/security/oauth2/user/NaverOAuth2UserInfo.java
  src/main/java/com/flux/fluxDomainLogin/security/oauth2/user/OAuth2UserInfo.java
  src/main/java/com/flux/fluxDomainLogin/security/oauth2/user/OAuth2UserInfoFactory.java
  src/main/java/com/flux/fluxDomainLogin/util/CookieUtils.java
Labels: developing

#39 Feat2
  src/main/java/com/flux/FluxApplication.java
  src/main/java/com/flux/auth/config/AppProperties.java
  src/main/java/com/flux/auth/config/SecurityConfig.java
  src/main/java/com/flux/auth/config/WebConfig.java
  src/main/java/com/flux/auth/config/WebMvcConfig.java
  src/main/java/com/flux/auth/controller/AuthController.java
  src/main/java/com/flux/auth/controller/MainController.java
  src/main/java/com/flux/auth/controller/OAuth2Controller.java
  src/main/java/com/flux/auth/controller/UserController.java
  src/main/java/com/flux/auth/dto/CustomOAuth2User.java
  src/main/java/com/flux/auth/dto/GoogleResponse.java
  src/main/java/com/flux/auth/dto/NaverResponse.java
  src/main/java/com/flux/auth/dto/OAuth2Response.java
  src/main/java/com/flux/auth/exception/BadRequestException.java
  src/main/java/com/flux/auth/exception/GlobalExceptionHandler.java
  src/main/java/com/flux/auth/exception/OAuth2AuthenticationProcessingException.java
  src/main/java/com/flux/auth/exception/ResourceNotFoundException.java
  src/main/java/com/flux/auth/model/AuthProvider.java
  src/main/java/com/flux/auth/model/User.java
  src/main/java/com/flux/auth/payload/ApiResponse.java
  src/main/java/com/flux/auth/payload/AuthResponse.java
  src/main/java/com/flux/auth/payload/LoginRequest.java
  src/main/java/com/flux/auth/payload/SignUpRequest.java
  src/main/java/com/flux/auth/repository/UserRepository.java
  src/main/java/com/flux/auth/security/CurrentUser.java
  src/main/java/com/flux/auth/security/CustomUserDetailsService.java
  src/main/java/com/flux/auth/security/RestAuthenticationEntryPoint.java
  src/main/java/com/flux/auth/security/TokenAuthenticationFilter.java
  src/main/java/com/flux/auth/security/TokenProvider.java
  src/main/java/com/flux/auth/security/UserPrincipal.java
  src/main/java/com/flux/auth/security/oauth2/CustomOAuth2UserService.java
  src/main/java/com/flux/auth/security/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/flux/auth/security/oauth2/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/flux/auth/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/flux/auth/security/oauth2/user/GoogleOAuth2UserInfo.java
  src/main/java/com/flux/auth/security/oauth2/user/NaverOAuth2UserInfo.java
  src/main/java/com/flux/auth/security/oauth2/user/OAuth2UserInfo.java
  src/main/java/com/flux/auth/security/oauth2/user/OAuth2UserInfoFactory.java
  src/main/java/com/flux/auth/service/CustomOAuth2UserService.java
  src/main/java/com/flux/auth/util/CookieUtils.java
  src/main/java/com/flux/salse/repository/SalesRepository.java
  src/main/java/com/flux/user/model/Role.java
  src/main/java/com/flux/user/model/User.java
  src/main/java/com/flux/user/model/UserDTO.java
  src/main/java/com/flux/user/repository/UserRepository.java
  src/main/java/com/flux/wish/repository/WishRepository.java
Labels: developing

#40 fix : article
  src/main/java/com/flux/article/controller/ArticleController.java
  src/main/java/com/flux/article/model/Article.java
  src/main/java/com/flux/article/model/ArticleDTO.java
  src/main/java/com/flux/article/repository/ArticleRepository.java
  src/main/java/com/flux/article/service/ArticleService.java
Labels: developing

#41 fix : market update
  src/main/java/com/flux/market/controller/MarketController.java
  src/main/java/com/flux/market/model/Market.java
  src/main/java/com/flux/market/model/MarketDTO.java
  src/main/java/com/flux/market/service/MarketService.java
Labels: complete

#44 chore : login code modify
  src/main/java/com/flux/auth/controller/OAuth2Controller.java
  src/main/java/com/flux/auth/dto/GoogleResponse.java
  src/main/java/com/flux/auth/service/CustomOAuth2UserService.java
  src/main/java/com/flux/auth/service/OAuth2Service.java
Labels: developing

#45 feat : wish update
  src/main/java/com/flux/wish/controller/WishController.java
  src/main/java/com/flux/wish/model/Wish.java
  src/main/java/com/flux/wish/model/WishDTO.java
  src/main/java/com/flux/wish/service/WishService.java
Labels: developing, complete

#46 feat : logout
  src/main/java/com/flux/auth/config/SecurityConfig.java
  src/main/java/com/flux/auth/config/WebConfig.java
  src/main/java/com/flux/auth/controller/OAuth2Controller.java
  src/main/java/com/flux/auth/dto/CustomOAuth2User.java
  src/main/java/com/flux/auth/service/OAuth2Service.java
  src/main/java/com/flux/market/controller/MarketController.java
  src/main/java/com/flux/user/model/User.java
Labels: developing

#48 feat : wish repository update
  src/main/java/com/flux/FluxApplication.java
  src/main/java/com/flux/wish/repository/WishRepository.java
Labels: complete

#50 fix : article post
  src/main/java/com/flux/article/controller/ArticleController.java
  src/main/java/com/flux/article/model/Article.java
  src/main/java/com/flux/article/model/ArticleDTO.java
  src/main/java/com/flux/article/service/ArticleService.java
Labels: complete

#51 fix:article
  src/main/java/com/flux/article/controller/ArticleController.java
  src/main/java/com/flux/article/model/Article.java
  src/main/java/com/flux/article/model/ArticleDTO.java
  src/main/java/com/flux/article/service/ArticleService.java
Labels: developing

#53 fix : wish cross-origin option
  src/main/java/com/flux/notice/controller/NoticeController.java
  src/main/java/com/flux/wish/controller/WishController.java
Labels: developing, complete

#54 feat : add API specification by swagger
  build.gradle
  src/main/java/com/flux/FluxApplication.java
  src/main/java/com/flux/auth/config/SecurityConfig.java
  src/main/java/com/flux/global/swagger/config/SwaggerConfig.java
  src/main/java/com/flux/notice/controller/NoticeController.java
  src/main/java/com/flux/notice/model/Notice.java
  src/main/java/com/flux/notice/model/NoticeDTO.java
  src/main/java/com/flux/notice/repository/NoticeRepository.java
  src/main/java/com/flux/notice/service/NoticeService.java
  src/main/java/com/flux/wish/controller/WishController.java
Labels: developing, complete

#55 fix : wish end-point update
  build.gradle
  src/main/java/com/flux/wish/controller/WishController.java
  src/main/java/com/flux/wish/service/WishService.java
Labels: developing, complete

#56 chore : login userId modify
  src/main/java/com/flux/auth/controller/OAuth2Controller.java
  src/main/java/com/flux/auth/repository/UserRepository.java
  src/main/java/com/flux/auth/service/OAuth2Service.java
  src/main/java/com/flux/user/model/User.java
Labels: complete

#58 feat : wish, notice swagger update
  src/main/java/com/flux/notice/controller/NoticeController.java
  src/main/java/com/flux/wish/controller/WishController.java
Labels: developing, complete

#59 feat : market sales goods save
  src/main/java/com/flux/market/controller/MarketController.java
  src/main/java/com/flux/market/model/Market.java
  src/main/java/com/flux/market/model/MarketDTO.java
  src/main/java/com/flux/market/repository/MarketRepository.java
  src/main/java/com/flux/market/service/MarketService.java
Labels: complete

#60 feat : comment method update
  src/main/java/com/flux/comment/controller/CommentController.java
  src/main/java/com/flux/comment/model/Comment.java
  src/main/java/com/flux/comment/repository/CommentRepository.java
  src/main/java/com/flux/comment/service/CommentService.java
Labels: developing, complete

#61 fix: article
  src/main/java/com/flux/article/controller/ArticleController.java
  src/main/java/com/flux/article/model/Article.java
  src/main/java/com/flux/article/model/ArticleDTO.java
  src/main/java/com/flux/article/service/ArticleService.java
  src/main/java/com/flux/auth/repository/UserRepository.java
  src/main/java/com/flux/user/model/User.java
  src/main/java/com/flux/user/service/UserService.java
Labels: developing

#66 fix : comment method
  src/main/java/com/flux/comment/controller/CommentController.java
  src/main/java/com/flux/comment/model/Comment.java
  src/main/java/com/flux/comment/service/CommentService.java
  src/main/java/com/flux/global/exception/ResourceNotFoundException.java
Labels: developing, complete

#67 fix:article
  src/main/java/com/flux/article/controller/ArticleController.java
  src/main/java/com/flux/article/model/ArticleDTO.java
  src/main/java/com/flux/article/service/ArticleService.java
Labels: developing

#68 fix : comment method update
  src/main/java/com/flux/comment/controller/CommentController.java
  src/main/java/com/flux/comment/model/Comment.java
  src/main/java/com/flux/comment/service/CommentService.java
Labels: developing, complete

#69 코멘트 테스트 코드 작성
  src/test/java/com/flux/comment/controller/CommentControllerTest.java
  src/test/java/com/flux/comment/service/CommentServiceTest.java
Labels: test-code

#70 fix : comment test-code update
  src/test/java/com/flux/comment/controller/CommentControllerTest.java
Labels: bug

#71 feat : user info controll
  src/main/java/com/flux/user/controller/UserController.java
  src/main/java/com/flux/user/model/Role.java
  src/main/java/com/flux/user/model/UserDTO.java
  src/main/java/com/flux/user/service/UserService.java
Labels: complete

#72 add domain service @Transactional
  src/main/java/com/flux/article/service/ArticleService.java
  src/main/java/com/flux/comment/service/CommentService.java
  src/main/java/com/flux/market/service/MarketService.java
  src/main/java/com/flux/wish/service/WishService.java
Labels: complete

#73 feat : visitor
  src/main/java/com/flux/user/controller/UserController.java
  src/main/java/com/flux/user/service/UserService.java
  src/main/java/com/flux/visitor/controller/VisitorController.java
  src/main/java/com/flux/visitor/model/Visitor.java
  src/main/java/com/flux/visitor/repository/VisitorRepository.java
  src/main/java/com/flux/visitor/service/VisitorService.java
Labels: developing

#74 feat : visitor modify
  src/main/java/com/flux/visitor/controller/VisitorController.java
  src/main/java/com/flux/visitor/model/Visitor.java
  src/main/java/com/flux/visitor/repository/VisitorRepository.java
  src/main/java/com/flux/visitor/service/VisitorService.java
Labels: developing

#75 feat:bid
  src/main/java/com/flux/article/controller/ArticleController.java
  src/main/java/com/flux/bid/controller/BidController.java
  src/main/java/com/flux/bid/model/Bid.java
  src/main/java/com/flux/bid/model/BidDTO.java
  src/main/java/com/flux/bid/model/BidStatus.java
  src/main/java/com/flux/bid/model/BuyNowRequest.java
  src/main/java/com/flux/bid/repository/BidRepository.java
  src/main/java/com/flux/bid/service/BidService.java
  src/main/java/com/flux/market/model/Market.java
  src/main/java/com/flux/market/model/MarketDTO.java
  src/main/java/com/flux/market/repository/MarketRepository.java
Labels: developing

#78 feat : visitor modify
  src/main/java/com/flux/visitor/repository/VisitorRepository.java
  src/main/java/com/flux/visitor/service/VisitorService.java
Labels: developing

#79 Feat5
  src/main/java/com/flux/article/controller/ArticleController.java
  src/main/java/com/flux/bid/controller/BidController.java
  src/main/java/com/flux/bid/model/Bid.java
  src/main/java/com/flux/bid/model/BidDTO.java
  src/main/java/com/flux/bid/model/BidStatus.java
  src/main/java/com/flux/bid/repository/BidRepository.java
  src/main/java/com/flux/bid/service/BidService.java
  src/main/java/com/flux/market/model/Market.java
  src/main/java/com/flux/market/model/MarketDTO.java
  src/main/java/com/flux/market/repository/MarketRepository.java
Labels: developing, complete

#80 feat : 관리자 메인 유저수 카운트 추가
  src/main/java/com/flux/user/controller/UserController.java
  src/main/java/com/flux/user/model/User.java
  src/main/java/com/flux/user/service/UserService.java
  src/main/java/com/flux/visitor/model/Visitor.java
Labels: developing

#81 fix : UserService transactional added
  src/main/java/com/flux/user/service/UserService.java
Labels: complete

#82 fix : UserService update
  src/main/java/com/flux/user/service/UserService.java
Labels: complete

#84 feat : 권한 설정
  src/main/java/com/flux/auth/config/SecurityConfig.java
  src/main/java/com/flux/auth/service/OAuth2Service.java
Labels: developing

#85 fix: market, bid
  src/main/java/com/flux/bid/controller/BidController.java
  src/main/java/com/flux/bid/repository/BidRepository.java
  src/main/java/com/flux/bid/service/BidService.java
  src/main/java/com/flux/market/controller/MarketController.java
  src/main/java/com/flux/market/model/Market.java
  src/main/java/com/flux/market/model/MarketDTO.java
  src/main/java/com/flux/market/service/MarketService.java
  src/main/resources/static/img/uploads/038c17bb4cf24b1caf5eded5e79485e7.jpg
  src/main/resources/static/img/uploads/13cecbdddacc40c8b5d0a01619ac073c.jpg
  src/main/resources/static/img/uploads/337376beb6fd4f89bcaab094ed351f35.jpg
  src/main/resources/static/img/uploads/432901bb3f8e4d2b954a9252f132e08b.jpg
  src/main/resources/static/img/uploads/50da5f1e4b9b48138d7f4c96a43d08a4.jpg
  src/main/resources/static/img/uploads/56b85f6c9e8249688059f2bffb1da105.jpg
  src/main/resources/static/img/uploads/5e8f19b7e56c453a864254a49274c902.jpg
  src/main/resources/static/img/uploads/602c8ef9308f4b4ba2026b0fb568f2b8.jpg
  src/main/resources/static/img/uploads/8fed402ce7a6439e8ff05906d4a324f0.jpg
  src/main/resources/static/img/uploads/a78c68d7bfea45909ab1fb63bc8d9bfc.jpg
  src/main/resources/static/img/uploads/b66ac39a07e54cbb9ec260b5a5e893f0.jpg
  src/main/resources/static/img/uploads/d6970aba6117438880a9ffe387374cd5.jpg
  src/main/resources/static/img/uploads/ffc2f901ddbc4c338173fd24440aa1f9.jpg
Labels: developing, complete

#86 fix: market
  src/main/java/com/flux/FluxApplication.java
  src/main/java/com/flux/bid/service/BidService.java
  src/main/java/com/flux/market/repository/MarketRepository.java
  src/main/java/com/flux/market/service/MarketService.java
Labels: developing, complete

#87 fix : mypage market
  src/main/java/com/flux/bid/repository/BidRepository.java
  src/main/java/com/flux/market/controller/MarketController.java
  src/main/java/com/flux/market/model/MarketDTO.java
  src/main/java/com/flux/market/repository/MarketRepository.java
  src/main/java/com/flux/market/service/MarketService.java
Labels: developing, complete

#88 chore : 이미지 수정
  src/main/java/com/flux/market/controller/MarketController.java
  src/main/java/com/flux/market/service/MarketService.java
Labels: developing

#89 chore : yml파일
  .gitignore
  src/main/resources/application.yml
Labels: complete

#92 fix:article endpoint
  src/main/java/com/flux/article/controller/ArticleController.java
Labels: developing, complete
